export const AGREGAR_CASOS_PRUEBA = "AGREGAR_CASOS_PRUEBA";
export const AGREGAR_CASOS_PRUEBA_EXITO = "AGREGAR_CASOS_PRUEBA_EXITO";
export const AGREGAR_CASOS_PRUEBA_ERROR = "AGREGAR_CASOS_PRUEBA_ERROR";

export const LISTAR_CASOS_PRUEBA = "LISTAR_CASOS_PRUEBA";
export const LISTAR_CASOS_PRUEBA_EXITO = "LISTAR_CASOS_PRUEBA_EXITO";
export const LISTAR_CASOS_PRUEBA_ERROR = "LISTAR_CASOS_PRUEBA_ERROR";

export const EDITAR_CASOS_PRUEBA = "EDITAR_CASOS_PRUEBA";
export const EDITAR_CASOS_PRUEBA_EXITO = "EDITAR_CASOS_PRUEBA_EXITO";
export const EDITAR_CASOS_PRUEBA_ERROR = "EDITAR_CASOS_PRUEBA_ERROR";

export const ELIMINAR_CASOS_PRUEBA = "ELIMINAR_CASOS_PRUEBA";
export const ELIMINAR_CASOS_PRUEBA_EXITO = "ELIMINAR_CASOS_PRUEBA_EXITO";
export const ELIMINAR_CASOS_PRUEBA_ERROR = "ELIMINAR_CASOS_PRUEBA_ERROR";

export const DESCARGAR_DOCUMENTO = "DESCARGAR_DOCUMENTO";
export const DESCARGAR_DOCUMENTO_EXITO = "DESCARGAR_DOCUMENTO_EXITO";
export const DESCARGAR_DOCUMENTO_ERROR = "DESCARGAR_DOCUMENTO_ERROR";

export const ORDENAR_CP = "ORDENAR_CP";
export const ORDENAR_CP_EXITO = "ORDENAR_CP_EXITO"; 
export const ORDENAR_CP_ERROR = "ORDENAR_CP_ERROR";