export const AGREGAR_PETICION = 'AGREGAR_PETICION';
export const AGREGAR_PETICION_EXITO = 'AGREGAR_PETICION_EXITO';
export const AGREGAR_PETICION_ERROR = 'AGREGAR_PETICION_ERROR';

export const COMENZAR_DESCARGA_PETICIONES = 'COMENZAR_DESCARGA_PETICIONES';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';
