/**
 * Types para agregar las peticiones
 */
export const AGREGAR_PETICION = 'AGREGAR_PETICION';
export const AGREGAR_PETICION_EXITO = 'AGREGAR_PETICION_EXITO';
export const AGREGAR_PETICION_ERROR = 'AGREGAR_PETICION_ERROR';

/**
 * Types para descargar las peticiones
 */
export const COMENZAR_DESCARGA_PETICIONES = 'COMENZAR_DESCARGA_PETICIONES';
export const DESCARGA_PETICIONES_EXITO = 'DESCARGA_PETICIONES_EXITO';
export const DESCARGA_PETICIONES_ERROR = 'DESCARGA_PETICIONES_ERROR';

/**
 * Types unicamente para el listado de proyectos
 */
export const LISTAR_PROYECTOS = 'LISTAR_PROYECTOS';
export const LISTAR_PROYECTOS_EXITO = 'LISTAR_PROYECTOS_EXITO';
export const LISTAR_PROYECTOS_ERROR = 'LISTAR_PROYECTOS_ERROR';

export const SELECCION_PROYECTO = 'SELECCION_PROYECTO';