/**
 * Types para la lista de planes de prueba
 */
export const OBTENER_PLANES_PRUEBA = 'OBTENER_PLANES_PRUEBA';
export const OBTENER_PLANES_PRUEBA_EXITO = 'OBTENER_PLANES_PRUEBA_EXITO';
export const OBTENER_PLANES_PRUEBA_ERROR = 'OBTENER_PLANES_PRUEBA_ERROR';

/**
 * Types para agregar el plan de prueba
 */
export const AGREGAR_PLAN_PRUEBA = 'AGREGAR_PLAN_PRUEBA';
export const AGREGAR_PLAN_PRUEBA_EXITO = 'AGREGAR_PLAN_PRUEBA_EXITO';
export const AGREGAR_PLAN_PRUEBA_ERROR = 'AGREGAR_PLAN_PRUEBA_ERROR';

/**
 * Types para editar
 */
 export const EDITAR_PLAN_PRUEBA = 'EDITAR_PLAN_PRUEBA';
 export const EDITAR_PLAN_PRUEBA_EXITO = 'EDITAR_PLAN_PRUEBA_EXITO';
 export const EDITAR_PLAN_PRUEBA_ERROR = 'EDITAR_PLAN_PRUEBA_ERROR';