export const GUARDAR_STEP = "GUARDAR_STEP";
export const GUARDAR_STEP_EXITO = "GUARDAR_STEP_EXITO";
export const GUARDAR_STEP_ERROR = "GUARDAR_STEP_ERROR";

export const ACTUALIZAR_STEP = "ACTUALIZAR_STEP";
export const ACTUALIZAR_STEP_EXITO = "ACTUALIZAR_STEP_EXITO";
export const ACTUALIZAR_STEP_ERROR = "ACTUALIZAR_STEP_ERROR";

export const DESCARGAR_STEP = "DESCARGAR_STEP";
export const DESCARGAR_STEP_EXITO = "DESCARGAR_STEP_EXITO";
export const DESCARGAR_STEP_ERROR = "DESCARGAR_STEP_ERROR";

