/**
 * Type para el logeo del usuario
 */
export const LOGEO_USUARIO = "LOGEO_USUARIO";
export const LOGEO_USUARIO_EXITO = "LOGEO_USUARIO_EXITO";
export const LOGEO_USUARIO_ERROR = "LOGEO_USUARIO_ERROR";

export const DESLOGEO_USUARIO = "DESLOGEO_USUARIO";
export const DESLOGEO_USUARIO_EXITO = "DESLOGEO_USUARIO_EXITO";
export const DESLOGEO_USUARIO_ERROR = "DESLOGEO_USUARIO_ERROR";
